spring:
  application:
    name: clubix-api
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

server:
  port: 8080

whatsapp:
  hook:
    verify-token: cashback
  outgoing:
    phoneId: ${WHATSAPP_PHONE_ID}
    metaUrl: "https://graph.facebook.com/v25.0/${whatsapp.outgoing.phoneId}/messages"
    token: ${WHATSAPP_API_TOKEN}

---
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:h2:mem:///clubixdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  flyway:
    url: jdbc:h2:mem:clubixdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa


app:
  scenario: customer_balance   # Cambia o deja vacío para no seed: app.scenario=

---
spring:
  config:
    activate:
      on-profile: dev
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/clubixdb
    username: clubix
    password: clubix
  flyway:
    url: jdbc:postgresql://localhost:5432/clubixdb
    user: clubix
    password: clubix

---
spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url: ${DB_R2DBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    url: ${DB_JDBC_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
